package org.example.service;

// service class is where we store methods that perform logical operators

import org.example.dao.CustomerDao;
import org.example.dao.CustomerDaoImpl;
import org.example.dao.DaoFactory;
import org.example.entity.Customer;
import org.example.entity.Transactions;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import java.util.Scanner;

public class CustomerService {

// take if user input and insert into database
    public static void insertCustomer() {
        Scanner scanner = new Scanner(System.in);
        Scanner scannerString = new Scanner(System.in);

// don't ask for the id it will be auto-generated by cpu
        System.out.println("Please enter the first and last name of the customer: ");
        String customerName = scanner.nextLine();
        System.out.println("Is the customer approved for an account here at Ryan's World Bank? yes/no");
        String customerApproval = scanner.nextLine();
        if ( customerApproval.equals("yes")) {
            //System.out.println("Please enter the year the customer opened the account: ");
            String yearJoined = String.valueOf(LocalDateTime.now());
            System.out.println("Please enter the customers initial deposit required to open account: ");
            float accountBalance = scanner.nextFloat();
            Customer customer = new Customer(customerName, yearJoined, accountBalance);
            CustomerDao customerDao = DaoFactory.getCustomerDao();
            customerDao.insert(customer);
        }
        else {
            System.out.println("Customer approval not granted. Please delete customer from database.");
        }

    }

    public static void getCustomerById() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter the customers Id# number: ");
        int id = scanner.nextInt();
        CustomerDao customerDao = DaoFactory.getCustomerDao();
        Customer customer = customerDao.getCustomerById(id);
        System.out.println("");
        System.out.println( customer.getCustomerName() + "'s current account balance is: $" + customer.getAccountBalance());

    }

    public static void getCustomerByName() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter the customers first and last name : ");
        String customerName = scanner.nextLine();
        CustomerDao customerDao = DaoFactory.getCustomerDao();
        Customer customer = customerDao.getCustomerByName(customerName);
        System.out.println("");
        System.out.println( customer.getCustomerName() + "'s current account balance is: $" + customer.getAccountBalance());


    }

    public static void getAllCustomers() {
        System.out.println("All Customers: ");
        CustomerDao customerDao = DaoFactory.getCustomerDao();
        List<Customer> customers = customerDao.getAllCustomers();
        for(Customer customer: customers) {
            System.out.println(customer);
        }
    }

    public static void getAllTransactions() {
        System.out.println("All Transactions: ");
        CustomerDao customerDao = DaoFactory.getCustomerDao();
        List<Transactions> transactions = customerDao.getAllTransactions();
        for (Transactions transactions1: transactions ) {
            System.out.println(transactions1);
        }
    }


    public static void updateCustomer() {
        Scanner scanner = new Scanner(System.in);
        Scanner scannerInt = new Scanner(System.in);
        Scanner scannerFloat = new Scanner(System.in);

// don't ask for the id it will be auto-generated by cpu
        System.out.println("What is the Id# of the customer you wish to update: ");
        int id = scannerInt.nextInt();
        System.out.println("Please enter the updated name of the customer: ");
        String customerName = scanner.nextLine();
        //System.out.println("Please enter the updated year the customer opened the account: ");
        String yearJoined = String.valueOf(LocalDateTime.now());
        System.out.println("Please enter the customers account balance: ");
        float accountBalance = scannerFloat.nextFloat();
        Customer customer = new Customer(id, customerName, yearJoined, accountBalance);
        CustomerDao customerDao = DaoFactory.getCustomerDao();
// now updates the customer
        customerDao.update(customer);
    }

    public static void approve() {
        Scanner scanner = new Scanner(System.in);
        Scanner scannerInt = new Scanner(System.in);

// don't ask for the id it will be auto-generated by cpu
        System.out.println("What is the Id# of the customer you wish to approve: ");
        int id = scannerInt.nextInt();
        System.out.println("Is the customer approved for an account here at Ryan's World Bank? yes/no");
        String approve = scanner.nextLine();
        if(approve.equals("no")){
            System.out.println("Customer not approved.");
            String customerName = "ACCOUNT REJECTED";
            Customer customer = new Customer(id, customerName);
            CustomerDao customerDao = DaoFactory.getCustomerDao();
            customerDao.approve(customer);
        }
        else if(approve.equals("yes")){
            System.out.println("Customer Approved!");
            System.out.println("Please enter the customers first and last name: ");
            String customerName = scanner.nextLine();
            Customer customer = new Customer(id, customerName);
            CustomerDao customerDao = DaoFactory.getCustomerDao();
            customerDao.approve(customer);
        }

    }

    public static void deleteCustomer() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter the id number of the customer you wish to delete: ");
        int id = scanner.nextInt();
        CustomerDao customerDao = DaoFactory.getCustomerDao();
        customerDao.delete(id);

    }
}
